Feature: Create an account in Online Shopping Web Application
Description : This feature will test a creating an account feature 

Scenario: User able to create an account with valid data 

Given : Open Choosed Browser Successfully
When : Enter URL Successfully
And : Click on Sign IN Link
And : Enter Email Address 
And : Click on Create an Account Button
And : Click on Register Button
Then : User able to create an account successfully